language: objective-c
osx_image: xcode10
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - SCHEME="CloudKitGDPR"
  matrix:
    - DESTINATION="OS=4.0,name=Apple Watch Series 3 - 42mm" POD_LINT="NO"
    - DESTINATION="OS=3.1,name=Apple Watch - 42mm"          POD_LINT="NO"

    - DESTINATION="OS=11.0,name=iPhone 8 Plus"              POD_LINT="YES"
    - DESTINATION="OS=9.0,name=iPad 2"                      POD_LINT="NO"

    - DESTINATION="OS=11.0,name=Apple TV 1080p"             POD_LINT="NO"
    - DESTINATION="OS=9.0,name=Apple TV 1080p"              POD_LINT="NO"

    - DESTINATION="arch=x86_64"                             POD_LINT="NO"
script:
  - set -o pipefail
  - git submodule update --init
  - xcodebuild -version

  # Build Framework in Debug mode
  - travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug build | xcpretty;

  # Build Framework in Release mode
  - travis_retry xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
